export const envConfig = {
	URI_APP_SELECTED: process.env.NEXT_PUBLIC_URI_APP_SELECTED || "",
	URI_PONDER_DEVELOPER: process.env.NEXT_PUBLIC_URI_PONDER_DEVELOPER || "",
	COINGECKO_API_KEY: process.env.NEXT_PUBLIC_COINGECKO_API_KEY || "",
	WAGMI_PROJECT_ID: process.env.NEXT_PUBLIC_WAGMI_PROJECT_ID || "",
	ENV: process.env.NEXT_PUBLIC_ENV || "",
};
