export const SOCIAL = {
	Github_contract: "",
	Github_dapp: "",
	GitLab: "",
	Telegram: "",
	Twitter: "",
	SubStack: "",
	Forum: "",
	Docs: "",
	DefiLlama: "",
	Uniswap_Mainnet: "",
	Uniswap_Polygon: "",
	Uniswap_Arbitrum: "",
	Uniswap_Optimism: "",
	Uniswap_WOFDPS_Polygon: "",
	Audit_Blockbite: "",
	Audit_Code4rena: "",
	Audit_Chainsecurity: "",
	Partner_Arktionariat: "",
	Partner_DfxSwiss: "",
	Partner_Ammer: "",
	Partner_Zipper: "",
};
